%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-exotica-examples
Version:        6.0.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS exotica_examples package

License:        BSD
URL:            https://github.com/ipab-slmc/exotica
Source0:        %{name}-%{version}.tar.gz

Requires:       python3-pykdl
Requires:       ros-noetic-exotica-aico-solver
Requires:       ros-noetic-exotica-cartpole-dynamics-solver
Requires:       ros-noetic-exotica-collision-scene-fcl-latest
Requires:       ros-noetic-exotica-core
Requires:       ros-noetic-exotica-core-task-maps
Requires:       ros-noetic-exotica-ddp-solver
Requires:       ros-noetic-exotica-double-integrator-dynamics-solver
Requires:       ros-noetic-exotica-ik-solver
Requires:       ros-noetic-exotica-ilqg-solver
Requires:       ros-noetic-exotica-ilqr-solver
Requires:       ros-noetic-exotica-levenberg-marquardt-solver
Requires:       ros-noetic-exotica-ompl-control-solver
Requires:       ros-noetic-exotica-ompl-solver
Requires:       ros-noetic-exotica-pendulum-dynamics-solver
Requires:       ros-noetic-exotica-pinocchio-dynamics-solver
Requires:       ros-noetic-exotica-python
Requires:       ros-noetic-exotica-quadrotor-dynamics-solver
Requires:       ros-noetic-exotica-scipy-solver
Requires:       ros-noetic-exotica-time-indexed-rrt-connect-solver
Requires:       ros-noetic-geometry-msgs
Requires:       ros-noetic-interactive-markers
Requires:       ros-noetic-robot-state-publisher
Requires:       ros-noetic-rviz
Requires:       ros-noetic-sensor-msgs
Requires:       ros-noetic-visualization-msgs
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-exotica-aico-solver
BuildRequires:  ros-noetic-exotica-core
BuildRequires:  ros-noetic-exotica-core-task-maps
BuildRequires:  ros-noetic-exotica-ik-solver
BuildRequires:  ros-noetic-exotica-val-description
BuildRequires:  ros-noetic-rostest
BuildRequires:  ros-noetic-rosunit
BuildRequires:  ros-noetic-sensor-msgs
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Package containing examples and system tests for EXOTica.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Nov 24 2020 Vladimir Ivan <v.ivan@ed.ac.uk> - 6.0.2-1
- Autogenerated by Bloom

* Tue Nov 17 2020 Vladimir Ivan <v.ivan@ed.ac.uk> - 6.0.1-1
- Autogenerated by Bloom

* Mon Nov 09 2020 Vladimir Ivan <v.ivan@ed.ac.uk> - 6.0.0-1
- Autogenerated by Bloom

