Name:           ros-melodic-exotica-python
Version:        5.0.0
Release:        0%{?dist}
Summary:        ROS exotica_python package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       assimp-python
Requires:       python-matplotlib
Requires:       ros-melodic-exotica-core
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-moveit-msgs
Requires:       ros-melodic-pybind11-catkin
Requires:       ros-melodic-shape-msgs
BuildRequires:  assimp-python
BuildRequires:  python-matplotlib
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-exotica-core
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-moveit-msgs
BuildRequires:  ros-melodic-pybind11-catkin
BuildRequires:  ros-melodic-shape-msgs

%description
Python bindings for EXOTica

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Wed Jan 09 2019 Wolfgang Merkt <wolfgang.merkt@ed.ac.uk> - 5.0.0-0
- Autogenerated by Bloom

